### ISSUE TITLE
tweetnacl.js

### ISSUE THREAD

**Issue by maxogden** [auditdrivencrypto/secret-handshake#2]
just curious if libsodium could be swapped out for tweetnacl.js for use in js environments without c++ module support

**Comment by dominictarr** [comment]
yes. I started on a polyfil over here
https://github.com/dominictarr/sodium-browserify

which is based on ecmascript compiled version of sodium (created by the sodium maintainer)
it needs a few more features, but it's totally doable. just a matter of writing a few tests and stuff.
I just havn't worked on it because i don't have an urgent need to javascript crypto.

@maxogden what are you thinking of doing with it? the scene around nacl/sodium bindings is a bit messy tbh. it needs a solid leveldb style push to get it really good.

**Comment by dominictarr** [comment]
oh yeah, chloride now provides a comprehensive set of polyfils for libsodium. (including both "fast" and "small") browser versions, and a node version.  https://github.com/dominictarr/chloride

**Comment by dominictarr** [comment]
could have been closed ages ago
